package com.lambdaschool.foundation.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "contexts")
public class Context extends Auditable {

    /**
     * The primary key (long) of the contexts table.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long contextId;

    /**
     * The description (String). Cannot be null and must be unique
     */
    @NotNull
    @Column(nullable = false, unique = true)
    private String description;

    /**
     * One to One relationship between context and survey
     * context connects to survey that contains a list of default questions for current context
     */
    @OneToOne
    @JoinColumn(name = "surveyId")
    private Survey survey;

    /**
     * Default constructor used primarily by the JPA.
     */
    public Context() {
    }

    /**
     * Given the params, create a new context object
     * <p>
     * contextId is autogenerated
     *
     * @param description The description (String) of the context
     * @param survey      The survey (Survey) connected to the context
     */
    public Context(String description, Survey survey) {
        this.description = description;
        this.survey = survey;
    }

    public long getContextId() {
        return contextId;
    }

    public void setContextId(long contextId) {
        this.contextId = contextId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description.toLowerCase();
    }

    public Survey getSurvey() {
        return survey;
    }

    public void setSurvey(Survey survey) {
        this.survey = survey;
    }

}
